# Site settings
title: Si-Chi
email: hello@simonchilds.com
description: >
  Hello! I'm Simon Childs. I lead the development team for
  a leading FinTech company based in Cardiff.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.simonchilds.net" # the base hostname & protocol for your site
twitter_username: simonlchilds
github_username:  csharpsi
stackoverflow: users/773208/simonlchilds

# Build settings
markdown: kramdown
